const logos = [
  { name: "Telegram", class: "ci ci-telegram", category: "technology" },
  { name: "Linkedin", class: "ci ci-linkedin", category: "services" },
  { name: "Facebook", class: "ci ci-facebook", category: "technology" },
  { name: "Instagram", class: "ci ci-instagram", category: "technology" },
  { name: "Discord", class: "ci ci-discord", category: "technology" },
  { name: "Twitter", class: "ci ci-twitter", category: "technology" },
  { name: "Whatsapp", class: "ci ci-whatsapp", category: "technology" },
  { name: "Meta", class: "ci ci-meta", category: "technology" },
  { name: "Amazon", class: "ci ci-amazon", category: "services" },
  { name: "Apple", class: "ci ci-apple", category: "technology" },
  { name: "Netflix", class: "ci ci-netflix", category: "entertainment" },
  { name: "Google", class: "ci ci-google", category: "technology" },
  { name: "Microsoft", class: "ci ci-microsoft", category: "technology" },
  { name: "aws", class: "ci ci-aws", category: "technology" },
  { name: "gcd", class: "ci ci-gcd", category: "technology" },
  { name: "azure", class: "ci ci-azure", category: "technology" },
  { name: "do", class: "ci ci-do", category: "technology" },
  { name: "railway", class: "ci ci-railway", category: "travel and tourism" },
  { name: "Vercel", class: "ci ci-vercel", category: "technology" },
  { name: "netlify", class: "ci ci-netlify", category: "technology" },
  { name: "Svelte", class: "ci ci-svelte", category: "technology" },
  { name: "Next.js", class: "ci ci-nextjs", category: "technology" },
  { name: "Nuxt.js", class: "ci ci-nuxtjs", category: "technology" },
  { name: "React.js", class: "ci ci-reactjs", category: "technology" },
  { name: "CIPHENSE", class: "ci ci-ciphense", category: "technology" },
  { name: "Pinia", class: "ci ci-pinia", category: "technology" },
  { name: "polygon.io", class: "ci ci-polygon-io", category: "technology" },
  { name: "transparent", class: "ci ci-transparent", category: "technology" },
];

export default logos;
