const logos2 = [
    { name: "Telegram", class: "ci ci-telegram" },
    { name: "Linkedin", class: "ci ci-linkedin" },
    { name: "Linkedin Horizontal", class: "ci ci-linkedin-horizontal" },
    { name: "Facebook", class: "ci ci-facebook" },
    { name: "Instagram", class: "ci ci-instagram" },
    { name: "Discord", class: "ci ci-discord" },
    { name: "Discord Horizontal", class: "ci ci-discord-horizontal" },
    { name: "Twitter", class: "ci ci-twitter" },
    { name: "Twitter Circle", class: "ci ci-twitter-circle" },
    { name: "Twitter Square", class: "ci ci-twitter-square" },
    {
      name: "Twitter Rounded Square",
      class: "ci ci-twitter-rounded-square",
    },
    { name: "Whatsapp", class: "ci ci-whatsapp" },
    { name: "Whatsapp 2", class: "ci ci-whatsapp2" },
    { name: "Whatsapp horizontal", class: "ci ci-whatsapp-horizontal" },
    { name: "Whatsapp2 horizontal", class: "ci ci-whatsapp2-horizontal" },
    { name: "Whatsapp vertical", class: "ci ci-whatsapp-vertical" },
    { name: "Whatsapp2 vertical", class: "ci ci-whatsapp2-vertical" },

    { name: "Meta", class: "ci ci-meta" },
    { name: "Meta Horizontal", class: "ci ci-meta-horizontal" },
    { name: "Amazon", class: "ci ci-amazon" },
    { name: "Apple", class: "ci ci-apple" },
    { name: "Netflix", class: "ci ci-netflix" },
    { name: "Netflix Wordmark", class: "ci ci-netflix-wordmark" },
    { name: "Google", class: "ci ci-google" },
    { name: "Google Wordmark", class: "ci ci-google-wordmark" },
    { name: "Microsoft", class: "ci ci-microsoft" },
    { name: "Microsoft Horizontal", class: "ci ci-microsoft-horizontal" },

    { name: "aws", class: "ci ci-aws" },
    { name: "gcd", class: "ci ci-gcd" },
    { name: "azure", class: "ci ci-azure" },
    { name: "azure2", class: "ci ci-azure2" },
    { name: "do", class: "ci ci-do" },
    { name: "do horizontal", class: "ci ci-do-horizontal" },
    { name: "do vertical", class: "ci ci-do-vertical" },
    { name: "railway", class: "ci ci-railway" },
    { name: "Vercel", class: "ci ci-vercel" },
    { name: "Vercel Horizontal", class: "ci ci-vercel-horizontal" },
    { name: "netlify", class: "ci ci-netlify" },
    { name: "netlify wordmark", class: "ci ci-netlify-wordmark" },

    { name: "Svelte", class: "ci ci-svelte" },
    { name: "Svelte Horizontal", class: "ci ci-svelte-horizontal" },
    { name: "Next.js", class: "ci ci-nextjs" },
    { name: "Next.js Horizontal", class: "ci ci-nextjs-horizontal" },
    { name: "Nuxt.js", class: "ci ci-nuxtjs" },
    { name: "React.js", class: "ci ci-reactjs" },

    { name: "CIPHENSE", class: "ci ci-ciphense" },
    { name: "Pinia", class: "ci ci-pinia" },
    { name: "polygon.io", class: "ci ci-polygon-io" },
    { name: "transparent", class: "ci ci-transparent" },
  ];

export default logos2;
