import "./globals.css";
import { Inter } from "next/font/google"; // Import the Inter font

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Colored-Icons",
  description: "Generated by Dheeresh Agarwal",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
       {/* Link to external stylesheet for colored icons */}
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/dheereshagrwal/colored-icons@master/ci.min.css"
        />
      </head>
       {/* Render the children (content) */}
      <body className="font-inter">{children}</body>
    </html>
  );
}
